language: php
sudo: false

php:
- '5.5'
- '5.6'
- '7.0'
- hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
- composer self-update

install:
- composer install --prefer-source

script:
- ./vendor/bin/phpunit -v

after_success:
- if [ $TRAVIS_PHP_VERSION = '7.0' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
- if [ $TRAVIS_PHP_VERSION = '7.0' ]; then sh ./scripts/publishCodeCoverage.sh; fi
