language: php
sudo: false

php:
- '5.5'
- '5.6'
- '7.0'
- hhvm

after_success:
- if [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
